import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useState } from "react";

export default function Home() {
  const [userDetails, setuserDetails] = useState({
    firstName: "",
    lastName: "",
    phoneNumber: "",
    email: "",
    password: "",
    confirmPassword: "",
  });

  const submitHandler = async (event) => {
    event.preventDefault();
    const response = await fetch("/api/register", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        // firstName: userDetails.firstName,
        // lastName: userDetails.lastName,
        // phoneNumber: userDetails.phoneNumber,
        // email: userDetails.email,
        // password: userDetails.password,
        // confirmPassword: userDetails.confirmPassword,
        ...userDetails,
      }),
    });

    const data = await response.json();
    console.log(data);
    if (!data.success) {
      alert(data.error);
    }
    else{
      alert(data.message);
    }
    setuserDetails({
      firstName: "",
      lastName: "",
      phoneNumber: "",
      email: "",
      password: "",
      confirmPassword: "",
    });
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.myUncode}>Uncode.</h1>
        <p>
          A Central Hub where teams can work,plan <br /> and achieve amazing
          things together.
        </p>
        <div className={styles.myForm}>
          <div>
            <Image src="/landing_pic.jpg" alt="" height={780} width={970} />
          </div>

          <div className={styles.headingDiv}>
            <div className={styles.infoDiv}>
              <h3 className={styles.myH3}>Start For Free</h3>
              <h1 className={styles.myH1}>Sign up to Uncode.</h1>
              <h3 className={styles.myH3}>
                <span style={{ color: "#e3866a" }}> Already a member? </span>
                <Link href="/login">
                  <a style={{ color: "#446e90" }}>Log in</a>
                </Link>
              </h3>
            </div>
            <form method="post" onSubmit={submitHandler}>
              <div className={styles.parentDiv}>
                <div className={styles.childDiv}>
                  <div>
                    <input
                      type="text"
                      name=""
                      id=""
                      placeholder="Enter First Name"
                      value={userDetails.firstName}
                      onChange={(e) => {
                        setuserDetails({
                          ...userDetails,
                          firstName: e.target.value,
                        });
                      }}
                      className={styles.myInput}
                    />
                  </div>

                  <input
                    type="text"
                    name=""
                    id=""
                    placeholder="Enter Phone Number"
                    value={userDetails.phoneNumber}
                    onChange={(e) => {
                      setuserDetails({
                        ...userDetails,
                        phoneNumber: e.target.value,
                      });
                    }}
                    className={styles.myInput}
                  />

                  <input
                    type="password"
                    name=""
                    id=""
                    placeholder="Enter Password"
                    value={userDetails.password}
                    onChange={(e) => {
                      setuserDetails({
                        ...userDetails,
                        password: e.target.value,
                      });
                    }}
                    className={styles.myInput}
                  />
                </div>
                <div className={styles.childDiv}>
                  <input
                    type="text"
                    name=""
                    id=""
                    placeholder="Enter Last Name"
                    value={userDetails.lastName}
                    onChange={(e) => {
                      setuserDetails({
                        ...userDetails,
                        lastName: e.target.value,
                      });
                    }}
                    className={styles.myInput}
                  />

                  <input
                    type="email"
                    name=""
                    id=""
                    placeholder="Enter Email"
                    value={userDetails.email}
                    onChange={(e) => {
                      setuserDetails({
                        ...userDetails,
                        email: e.target.value,
                      });
                    }}
                    className={styles.myInput}
                  />

                  <input
                    type="password"
                    name=""
                    id=""
                    value={userDetails.confirmPassword}
                    onChange={(e) => {
                      setuserDetails({
                        ...userDetails,
                        confirmPassword: e.target.value,
                      });
                    }}
                    placeholder="Enter Confirm Password"
                    className={styles.myInput}
                  />
                </div>
              </div>
              <div className={styles.buttonDiv}>
                {/* <Link href="/api/register">
                <a className={styles.myButton} onClick={submitHandler}>
                  Create an Account
                </a>
              </Link> */}
                <button type="submit" className={styles.myButton}>
                  Create an Account
                </button>
                {/* <a href="/api/register" className={styles.myButton} onClick={submitHandler}>
                Create an Account
              </a> */}
              </div>
            </form>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        Made With
        <span className={styles.logo}>
          <Image src="/heart32.png" alt="" width={18} height={18} />
        </span>
        &nbsp; by Vansh
      </footer>
    </div>
  );
}
