import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.myUncode}>Uncode.</h1>
        <p>
          A Central Hub where teams can work,plan <br /> and achieve amazing
          things together.
        </p>
        <div className={styles.myForm}>
          <div>
            <Image src="/landing_pic.jpg" alt="" height={780} width={970} />
          </div>

          <div className={styles.headingDiv}>
            <div className={styles.infoDiv}>
              <h3 className={styles.myH3}>Start For Free</h3>
              <h1 className={styles.myH1}>Sign up to Uncode.</h1>
              <h3 className={styles.myH3}>
                <span style={{ color: "#e3866a" }}> Already a member? </span>
                <Link  href="/login">
                <a style={{ color: "#446e90" }}>
                  Log in
                </a>
                </Link>
                
              </h3>
            </div>
            <div className={styles.parentDiv}>
              <div className={styles.childDiv}>
                <div>
                  <input
                    type="text"
                    name=""
                    id=""
                    placeholder="Enter First Name"
                    className={styles.myInput}
                  />
                </div>

                <input
                  type="text"
                  name=""
                  id=""
                  placeholder="Enter Phone Number"
                  className={styles.myInput}
                />

                <input
                  type="password"
                  name=""
                  id=""
                  placeholder="Enter Password"
                  className={styles.myInput}
                />
              </div>
              <div className={styles.childDiv}>
                <input
                  type="text"
                  name=""
                  id=""
                  placeholder="Enter Last Name"
                  className={styles.myInput}
                />

                <input
                  type="email"
                  name=""
                  id=""
                  placeholder="Enter Email"
                  className={styles.myInput}
                />

                <input
                  type="password"
                  name=""
                  id=""
                  placeholder="Enter Confirm Password"
                  className={styles.myInput}
                />
              </div>
            </div>
            <div className={styles.buttonDiv}>
              <a href="#" className={styles.myButton}>
                Create an Account
              </a>

              {/* <a href="#" className={styles.myButton}>
                Sign Up With Google
              </a> */}
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
   
        Made With
        <span className={styles.logo}>
          <Image src="/heart32.png" alt="" width={18} height={18} />
        </span>
        &nbsp; by Vansh
      
      </footer>
    </div>
  );
}
